### ISSUE TITLE
Will the code be available soon?

### ISSUE THREAD

**Issue by 5k5000** [yyvhang/lemon_3d#1]
Hi, thanks for sharing your great work!  Will the code be available soon?

**Comment by yyvhang** [comment]
> Hi, thanks for sharing your great work! Will the code be available soon?

Thanks for your interest. The code will be released in two weeks, stay tuned.

**Comment by 5k5000** [comment]
thanks！

**Comment by yyvhang** [comment]
The code and pre-trained model has been released!
