### ISSUE TITLE
About Visualization

### ISSUE THREAD

**Issue by AmingWu** [yyvhang/lemon_3d#12]
Dear Authors,

I have run the demo successfully. But when I visualize the corresponding testing data, how to obtain the corresponding Backpack_curvature.pkl, Backpack_human_demo.npz, and Backpack_object_demo.txt? Could you tell me how to find these files from your given dataset?

Thanks.

**Comment by yyvhang** [comment]
Please refer to this [instruction](https://github.com/yyvhang/lemon_3d/blob/main/Data/DATA.md), you can find each data in the dataset, e.g. the `Backpack_human_demo.npz` is the SMPL-H parameters, you can find them in the `human_label.json`

**Comment by AmingWu** [comment]
Thanks. Could you give an example? For example, I have found the Baseballbat_grasp_259.jpg and Baseballbat_grasp_259_mask.png. How to obtain the other files?

**Comment by AmingWu** [comment]
Besides, I want to visualize the contact type. Does it need six files?

**Comment by AmingWu** [comment]
The Objects file does not contain testing files.

**Comment by yyvhang** [comment]
You can check the [dataset class](https://github.com/yyvhang/lemon_3d/blob/ea81f22fe0648fa3e14364f27a55589b4f42c58d/dataset_utils/dataset_3DIR.py#L31) to see how to obtain the other files. The val.txt indicates the testing files.

**Comment by AmingWu** [comment]
Dear Authors,

Do you mean that I should run dataset class?

**Comment by AmingWu** [comment]
In your given inference code, you give a visualization example. But I want to visualize the other result. How to obtain the corresponding files? I do not understand your response. Could you give detailed interpretations?

Thanks

**Comment by yyvhang** [comment]
run inference_batch like [this](https://github.com/yyvhang/lemon_3d/blob/ea81f22fe0648fa3e14364f27a55589b4f42c58d/inference.py#L272)
