### ISSUE TITLE
How to Match Images with Corresponding 3D Point Clouds in the Dataset?

### ISSUE THREAD

**Issue by likanchuan09171** [yyvhang/lemon_3d#14]
Dear Authors:

Thank you for providing this great dataset. I tried to match the images with the corresponding 3D point clouds, but I have encountered some issues.

I initially tried matching them directly based on the default order in val.txt and Point_val.txt from the txt_scripts directory(e.g. Data/Objects/Earphone/Earphone_79.txt and Data/Images/Earphone/listen/Earphone_listen_78.jpg, as they both are in the first line of files). However, after visualizing the results, it appears that the image and point cloud pairs are not correctly aligned.

Could you please clarify the correct approach for matching the images with their respective 3D point clouds? Thanks for your help!

**Comment by yyvhang** [comment]
Thanks for your interest. Actually, the number of images and point clouds in the training set is not one-by-one pair. LEMON's setting emphasizes general understanding, that is, 3D objects only need to maintain the same category as objects in the image. During training, a 3D object instance of the same category will be randomly selected based on the objects in the image for training, please refer to the dataloader [code](https://github.com/yyvhang/lemon_3d/blob/main/dataset_utils/dataset_3DIR.py).

The benefit of this setting is that the model can generalize to different 3D instances of the same category, as shown in the main paper Figure 9. Hope this can address your concerns.

**Comment by likanchuan09171** [comment]
Thanks for your reply! This solved my confusion.
