### ISSUE TITLE
About the name of joints and vertices index data

### ISSUE THREAD

**Issue by labGoku** [yyvhang/lemon_3d#15]
Thanks for your excellent work. Please teach us how to know the joint name of the SMPLH data that your work used (and vertices index).

**Comment by yyvhang** [comment]
The joints: refer to [here](https://github.com/vchoutas/smplx/blob/main/smplx/joint_names.py)
The vertices: refer to [here](https://github.com/vchoutas/smplx/blob/main/smplx/vertex_ids.py)

**Comment by labGoku** [comment]
Thank you for your guidance.
