### ISSUE TITLE
Predict one single image.

### ISSUE THREAD

**Issue by Sharpiless** [yyvhang/lemon_3d#3]
Hi, awesome work! But how can i process a single custom image into the input format, including human_param, mask, and so on?

**Comment by yyvhang** [comment]
Hi, maybe you should first know about the [SMPL](https://smpl.is.tue.mpg.de/) series. And some methods could be used to obtain the human_param, like [OSX](https://github.com/IDEA-Research/OSX), [SMPLerX](https://github.com/caizhongang/SMPLer-X). Note that we use the SMPL-H, so I suggest using the method that can infer hand parameters. For mask, you can use [Grounded-SAM](https://github.com/IDEA-Research/Grounded-Segment-Anything) to predict the human and object mask or just manually annotate through this [tool ](https://github.com/yatengLG/ISAT_with_segment_anything).

If you do not use the curvature, the above are enough. For curvature, use
`trimesh.curvature.discrete_mean_curvature_measure` or `trimesh.curvature.discrete_gaussian_curvature_measure` for mesh data. [CouldCompare](https://www.danielgm.net/cc/) can also be used to calculate curvatures for point cloud data.
