### ISSUE TITLE
SMPL-H used in AMASS project

### ISSUE THREAD

**Issue by luban31** [yyvhang/lemon_3d#6]
I cant find SMPLH_NEUTRAL.pkl, can you  provide it?

**Comment by yyvhang** [comment]
Hi, download from this [url](https://drive.google.com/file/d/1Of_fIStrcLSp0Udt3jgNAa_7rphd1gbd/view?usp=sharing).

**Comment by soberguo** [comment]
![20241227171107](https://github.com/user-attachments/assets/47c001ab-9ad6-4a16-ab01-6f4f91544e83)

Sorry, I can't open this link

**Comment by soberguo** [comment]
Sorry, I can't open this link
![20241227171107](https://github.com/user-attachments/assets/177f477e-12d9-470d-815c-0e5add701893)

**Comment by yyvhang** [comment]
I have shared this with you, please check your email.

**Comment by soberguo** [comment]
Thank you very much

**Comment by soddday** [comment]
@yyvhang @soberguo I also need SMPLH_NEUTRAL.pkl, can you share it with me?

**Comment by jtyc12** [comment]
@yyvhang @soberguo I also need SMPLH_NEUTRAL.pkl, can you share it with me?thanks a lot!
