### ISSUE TITLE
About smpl_neutral_geodesic_dist.npy

### ISSUE THREAD

**Issue by AmingWu** [yyvhang/lemon_3d#8]
Dear Authors,

I have not found smpl_neutral_geodesic_dist.npy.  Could you share it with me?

Thanks.

**Comment by yyvhang** [comment]
Hi, download from this url: https://rich.is.tue.mpg.de/download.php
<img width="1075" alt="image" src="https://github.com/yyvhang/lemon_3d/assets/94104185/73e8d872-32bf-47e6-9f24-23e485337f84">
